### ISSUE TITLE
Use Markdown instead of HTML formatting on README.md

### ISSUE THREAD

**Issue by nicksuch** [david-vanderhaar/david-vanderhaar.github.io#1]
Nice work getting all your links into the README, and getting it all pushed to GitHub! One thing you could improve is to switch from HTML to Markdown formatting for your content. Check out how I did [my README](https://github.com/nicksuch/nicksuch.github.io/blob/master/README.md) as an example (clicking the `Raw` button may help you see my actual code), and see the [Markdown Syntax reference](https://daringfireball.net/projects/markdown/syntax), specifically for Lists and Links.

Great job figuring out the HTML here for tables, just wanted to save you a bit of code utilizing the simpler Markdown syntax. Markdown is something that will be helpful for our blog posts during the Bootcamp.

**Comment by david-vanderhaar** [comment]
Thank you! I was definitely confused about the README for awhile, this helps a ton.
