### ISSUE TITLE
HTML fixes

### ISSUE THREAD

**Issue by nicksuch** [david-vanderhaar/david-vanderhaar.github.io#2]
Nice work on this @david-vanderhaar ! Page looks great. A few quick tips to make it even better:

1. Use the `<img>` tag instead of `<image>`. While this works sometimes, it [doesn't work reliably](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/image).
2. Computers hate spaces :( But they like hyphens and underscores! For your `/Social Media Icons` directory, try [removing the spaces](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles) and instead using something like `/social-media-icons/` (and when possible, lowercase is better than Capital case)
3. It looks like you're missing a closing div tag `</div>` somewhere
4. Your Google+ link currently goes to Gmail.com (which, personally, is my most used social media platform!)

Let me know if you have any questions, and keep up the great work!

**Comment by david-vanderhaar** [comment]
Thanks again! This is very helpful. I can't believe I was getting by with a missing </div> tag. I just read in Eloquent JS that JS isn't so beginner friendly because it accepts a lot of wrong syntax without notifying the author. This is a good example :D Thank you for catching that!
